name: Create Tool Cache for create-or-update-comment@v4
on: push

jobs:
  create_tool_cache:
    runs-on: windows-latest
    steps:
      - name: Clear any existing tool cache
        shell: powershell
        run: |
          Remove-Item -Path "${{ runner.tool_cache }}\.tool_cache" -Recurse -Force
          New-Item -ItemType Directory -Path "${{ runner.tool_cache }}\.tool_cache"

      - name: Download create-or-update-comment action
        shell: powershell
        run: |
          git clone https://github.com/peter-evans/create-or-update-comment.git "${{ runner.tool_cache }}\.tool_cache\create-or-update-comment"

      - name: Archive tool cache
        shell: powershell
        run: |
          Compress-Archive -Path "${{ runner.tool_cache }}\.tool_cache" -DestinationPath "${{ runner.tool_cache }}/tool_cache.tar.gz"

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          name: tool_cache
          path: ${{ runner.tool_cache }}/tool_cache.tar.gz
