name: Create a comment on new issues

on:
  issues:
    types: [opened]

permissions: write-all

jobs:
  comment-with-action:
    runs-on: windows-latest
    steps:
      - name: "Dump GitHub Context"
        id: issueJsonObject
        run: |
          $json = '${{ toJson(github.event) }}'
        shell: pwsh

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: windows-latest
    steps:
      - name: Create comment with API
        shell: pwsh
        run: |
          $url = "https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments"
          $body = 'Comment but from the API call not action'
          Invoke-WebRequest -Uri $url -Method Post -Headers @{
            "Accept" = "application/vnd.github+json"
            "Authorization" = "Bearer $GITHUB_TOKEN"
            "X-GitHub-Api-Version" = "2022-11-28"
          } -Body $body -ContentType "application/json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}